### ISSUE TITLE
Crop applied to additional images

### ISSUE THREAD

**Issue by raphaelokon** [raphaelokon/TYPO3.CMS#12]
When dealing with more than one image in an element cropping only the first also applies a crop to the second.

**Comment by raphaelokon** [comment]
Is this still a thing @helhum ?

**Comment by helhum** [comment]
nope. solved by setting a bunch of properties to null: https://github.com/raphaelokon/TYPO3.CMS/blob/master/typo3/sysext/backend/Resources/Private/TypeScript/ImageManipulation.ts#L898-L900 on destroy
