### ISSUE TITLE
The first (not the last) breakpoint should be selected by default in the UI

### ISSUE THREAD

**Issue by helhum** [raphaelokon/TYPO3.CMS#8]
When opening the cropper, the first breakpoint should be shown.
Currently it shows the last

**Comment by raphaelokon** [comment]
Is this one resolved yet?

**Comment by helhum** [comment]
I'll take care

**Comment by raphaelokon** [comment]
Any progress on this?

**Comment by helhum** [comment]
resolved

Current state now is (and will be in the future) here: https://review.typo3.org/51515
